security:
#    factories:
#        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"
        
    providers:
#        in_memory:
#            users:
#                ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                admin: { password: kitten, roles: 'ROLE_ADMIN' }
        fos_userbundle:
            id: fos_user.user_manager
#        fos_twitter:
#            id: my.twitter.user
    
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
#        Symfony\Component\Security\Core\User\User: plaintext