<?php

namespace Koyaan\BsBotBundle\BotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuzzwordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuzzwordRepository extends EntityRepository
{
}