<?php

namespace Koyaan\GlobeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobeRepository extends EntityRepository
{
}